### ISSUE TITLE
Deletion job fails in versioning is not enabled

### ISSUE THREAD

**Issue by pabloredo** [awslabs/amazon-s3-find-and-forget#255]
Even when mapper ignores deletion of old version, job fails with message:}
"Error":"Unprocessable message: Bucket xxxxxxxx does not have versioning enabled". should be able to proceed or have the option to disable versioning check.

**Comment by matteofigus** [comment]
Hi, unfortunately buckets without version enabled are not supported as mentioned here: https://github.com/awslabs/amazon-s3-find-and-forget/blob/master/docs/LIMITS.md#other-limitations

The setting you mention is a bit different, that's about deleting or not previous versions of an object.

Can you tell us a bit more about the use-case and why enabling versioning would be a problem?

In our case, the reason on this limit is that it's the only way we can afford to have strong guarantees in terms of data consistency and prevent data loss. Without versioning, we wouldn't be able to do that.
