### ISSUE TITLE
Can't create a new data mapper when there is a glue table without any partition keys

### ISSUE THREAD

**Issue by linji0801** [awslabs/amazon-s3-find-and-forget#265]
Hi 

I just found a bug when trying to create a new data mapper. Just right after I clicked `Create Data Mapper` button, an error was thrown as below.
```
An error happened. 
TypeError: Cannot read property 'map' of undefined
```

It turned out that it's because some of glue tables don't contains partition keys and thus it will throw error [here](https://github.com/awslabs/amazon-s3-find-and-forget/blob/dfdda2d479ce62aed49f1d2ceeb28569be7598b6/frontend/src/utils/glueSerializer.js#L188). this issue will be fixed by adding a check condition here, which is like below.
```
partitionKeys: e.PartitionKeys ? /keep same/ : []
```

Hope you could fix this bug on your end.

Thanks
David

**Comment by matteofigus** [comment]
Hi @linji0801 , good catch, thanks for submitting the issue. Would you like to attempt a PR for the fix? Otherwise I can do it.

**Comment by linji0801** [comment]
Sure. I can submit a CR for it.

**Comment by linji0801** [comment]
I just submitted a [PR](https://github.com/awslabs/amazon-s3-find-and-forget/pull/266). Please review it when you get a chance. Thanks

**Comment by linji0801** [comment]
And another small issue I encountered is while I was creating a new data mapper, it didn't allow to select columns with `decimal` type from the selected glue table. Is there a way to enable decimal type? Thanks

**Comment by matteofigus** [comment]
Hi, `decimal` unfortunately is not available yet as column identifier. It shouldn't be hard to add support, but it requires edits behind frontend. 
Can I ask you to open a separate issue for that so we keep track? I can pick that one up.
