### ISSUE TITLE
Data Mappers - Unknown error (403 status code)

### ISSUE THREAD

**Issue by davorceman** [awslabs/amazon-s3-find-and-forget#269]
Hello,

I'm just trying this solution, it would be very useful for our case.
But after I deployed the stack, I'm getting this error:
> Unknown error (403 status code)
> POST https://sts.eu-west-1.amazonaws.com/?Action=GetCallerIdentity&Version=2011-06-15 403

I also checked CloudWatch log groupof a GetDataMappers Lambda and I don't see any error there
What I missed in process of deploying?

Here are the parameters I provided:
```AccessControlAllowOriginOverride	false	-
AccessLogsBucket	-	-
AdminEmail	mymailbox@example.com	-
AthenaConcurrencyLimit	20	-
AthenaWorkGroup	test	-
CognitoAdvancedSecurity	OFF	-
CreateCloudFrontDistribution	true	-
DeletionTaskCPU	4096	-
DeletionTaskMemory	30720	-
DeletionTasksMaxNumber	3	-
DeployVpc	false	-
EnableAPIAccessLogging	false	-
EnableContainerInsights	false	-
EnableDynamoDBBackups	false	-
FlowLogsGroup	-	-
FlowLogsRoleArn	-	-
ForgetQueueWaitSeconds	30	-
JobDetailsRetentionDays	0	-
KMSKeyArns	-	-
PreBuiltArtefactsBucketOverride	false	-
QueryExecutionWaitSeconds	3	-
QueryQueueWaitSeconds	3	-
ResourcePrefix	S3F2	-
RetainDynamoDBTables	true	-
VpcSecurityGroups	sg-123456789	-
VpcSubnets	subnet-123456,subnet-456789,subnet-789123 (private subnets)	-

**Comment by matteofigus** [comment]
Hi, 
1) Where do you see the error? Frontend? Calling the API? Both?
2) If you see it in the frontend, can you successfully authenticate first?
3) Did you deploy the stack with your own existing VPC? If yes, do you have the necessary VPC endpoints for accessing the services as explained [here](https://github.com/awslabs/amazon-s3-find-and-forget/blob/master/docs/USER_GUIDE.md#configuring-a-vpc-for-the-solution)?

**Comment by davorceman** [comment]
Hello, thx for quick response.

1. Just frontend, did not try API
2. Yes I was successfully authenticated.
3. Own existing VPC, I missed that part and I will try it tomorrow and update you.

Thank you!

**Comment by davorceman** [comment]
Hello again,

I deployed all these VPC endpoints, but issue was still there.
Then I decided to try with VPC from template. I removed my stack completely and deployed it with DeployVPC = True
And again, even with VPC deployed from CF, issue is still there.

Then I tried on fresh new AWS account just to check if maybe Organizational SCP making these problems. But no, issue is the same.

I still don't get what I'm missing

1. I have full admin access to AWS account
2. Tried to deploy it in Ireland
3. CF is deployed successfully, also the second one for IAM role
4. Parameters I'm using are default, you can find in first post
5. I'm able to log in to the Frontend, 
6. All pages works, only Data Mappers showing 403 error, look at screenshots below
7. I created successfully one Data Mapper, but it is not displayed on Data Mapper page because of a 403 error. I know that it is deployed because when I try to create one more with the same name, I'm getting warning that Data Mapper with that name already exist.
8. When I used with my VPC I also tried just for any case to deploy NAT gateway in public subnet, and also for testing I added ingress rule 0.0.0.0/0  to all traffic in that default SG.

**Comment by matteofigus** [comment]
Ok. I think that what's failing here is a call made from the frontend to the STS service directly, defined by this role:
https://github.com/awslabs/amazon-s3-find-and-forget/blob/23a0999133a8c9eac858f08487d7248c953b22b8/templates/auth.yaml#L82-L84

If this is failing, I guess we could either be having a CORS issue (but I cannot reproduce with latest Firefox/Chrome) or a conflict in the permissions. In this page there are multiple types of errors that may trigger a 403 https://docs.aws.amazon.com/STS/latest/APIReference/CommonErrors.html. From the screenshot, it seems like you are using Chrome: if you click the Network Tab and then click to the 403 error response, are you able to see any indication of the error code as part of the response?

**Comment by davorceman** [comment]
This is the error
> {"Error":{"Code":"SignatureDoesNotMatch","Message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.","Type":"Sender"},"RequestId":"6141cbb0-61a3-4c2d-ac04-7422dde94699"}

**Comment by matteofigus** [comment]
Thanks for being patient. I actually managed to reproduce locally by re-running a clear npm install - I think this bug was introduced when we upgraded some frontend libraries. I have a PR with a fix, give it some time and I'll let you know when the fix is published.

**Comment by matteofigus** [comment]
v0.34 is now published - can you upgrade the stack to the latest version and verify the bug is fixed? Thanks for your help.

**Comment by davorceman** [comment]
Nice work!
It works, now after I'm able to use Data Mappers page I can continue testing to see if it will work as a solution before we migrate from BigQuery to AWS :).

Thank you for great support!
