### ISSUE TITLE
[question] How to refer to exact version of CF template?

### ISSUE THREAD

**Issue by davorceman** [awslabs/amazon-s3-find-and-forget#288]
I'm deploying CF via TF, and I want to refer to template url like this
https://solution-builders-us-east-2.s3.us-east-2.amazonaws.com/amazon-s3-find-and-forget/latest/template.yaml

But how to find versioned urls, instead using the latest?

**Comment by ctd** [comment]
Hello,

You can replace the `latest` keyword with the version tag you want to target - e.g. `https://solution-builders-us-east-2.s3.us-east-2.amazonaws.com/amazon-s3-find-and-forget/v0.42/template.yaml` for `v0.42`.

**Comment by davorceman** [comment]
Thank you, tried already but forgot to add v :)
