### ISSUE TITLE
[Question] Set Glue bookmark feature request

### ISSUE THREAD

**Issue by davorceman** [awslabs/amazon-s3-find-and-forget#291]
Hello,

Firstly, sorry because I'm asking on wrong place.

just found some obvious thing I was not thinking earlier.

So, after S3F2 finish and update the file in our data lake, since we are using Glue bookmarks, next job run will take those files and reprocess.
Since there is no upsert logic for writing Glue dynamic frame, at the endpoint we will have duplicated records. Records which are remain in the parquet data and are not deleted via S3F2.

I know that we could resolve this with one step in the middle in our job, connecting to Redshift and with DDL to write data to temp table, and then find the records in the main, delete records, and then merge these two tables, but we decided to not do that since we have about 1000 tables, and we thought that we will not have changes back in the time.
So in case we need,. we thought that it would be easier to reset bookmark, drop table in redshift and then run the job again.

I know that I can manually comment code in glue related to job itself and writing to Redshift, but is there some nicer flow I can do?

I think that it would be mega useful to have Glue "Set bookmark" option, not just reset. So to set on current data in S3 bucket without running job.

Finally, my question is... could you please direct me where I can create that Glue Feature Request, because I have no idea? :)

**Comment by matteofigus** [comment]
Closing this because unrelated to S3 Find and Forget. @davorceman I believe you contacted me in private before - can you please get in touch so that I can explain about getting this feature request to the Glue team.
