### ISSUE TITLE
Stop a Deletion Job

### ISSUE THREAD

**Issue by abhra-gupta-trakstar** [awslabs/amazon-s3-find-and-forget#334]
I have a Deletion Job that is running for more than 24 Hours now. Is there a way to stop a Deletion Job?

**Comment by matteofigus** [comment]
You can manually stop the main Step function, and that should fail the job. There isn't currently a clear API endpoint/UI action to stop a running job unfortunately.

**Comment by abhra-gupta-trakstar** [comment]
Thanks @matteofigus. When I manually fail the job that way, I still have the deletion queue size the same when the Deletion Job started. Is there a way I can empty the Deletion Queue before I add new elements to the Queue and re-start the Job ?

**Comment by matteofigus** [comment]
It's hard to me to establish the reason of the failure. How is your Job Configuration in terms of Memory, vCPU and max tasks? You should be able to see these settings in the Job page.

**Comment by abhra-gupta-trakstar** [comment]
Here are the Job Settings and the stack parameters in Cloud Formation. They haven't been changed since deployment. Moreover, they have the same values in my QA and Production. I had previously looked up the Troubleshooting Guide where you have mentioned checking the StateMachine Logs and Lambda Function Logs in CLoudWatch and I don't see anything super weird. I am not sure how AWS Fargate works or if the containers have exhausted memory or vCPUs. 
 
![Screenshot 2022-09-16 at 9 35 04 AM](https://user-images.githubusercontent.com/89824590/190555885-b687bf1f-0c06-43d7-9184-957669691f6a.png)
![Screenshot 2022-09-16 at 9 51 20 AM](https://user-images.githubusercontent.com/89824590/190556086-4a7e33e0-3ccf-444f-b8f4-8556516ec420.png)

**Comment by abhra-gupta-trakstar** [comment]
Hi @matteofigus 
The Deletion Jobs are failing with a 'FORGET_FAILED' error after running for about 24 hours. I checked the job log for a `ForgetPhaseFailed` event. After further analysing the error, it was seen that the State Machine 'S3F2-DeletionStateMachine' execution is failing.

To understand the cause of State Machine execution failure, I verified the execution event history and found that the execution is failing with States.Runtime error as the execution history is exceeding the 25,000 hard limit.

Moving further, to find out why the execution went into a long running execution, I analysed the events and found that the execution is continuously transitioning in between the states: Wait -> Fetch Queue Size Again -> Queue is Empty? -> Wait. Also by comparing the successful and failed executions, I can understand that the execution that went in loop in between the Wait -> Fetch Queue Size Again -> Queue is Empty? -> Wait states, has failed with State.Runtime error. However, the executions which transitioned to next state 'Fetch Task Count' finished successfully.

Looking at the choice state 'Items in Queue?', I understand that the execution can transition to next state 'Fetch Task Count' only when "$.DesiredCount" and $.Queue.Total" attributes returned by Lambda function 'S3F2-StateMachineStack-16VHACBHOXRM-CheckQueueSize-gt5sL7uwBSHX' equals to 0.

However, I found that these attributes returned by Lambda function in each iteration are stable and are greater than 0 always. To verify this, I have filtered the execution events using filter as: 'Type=TaskStateExited' and 'State=Fetch Queue Size Again'. From this, I understood that though the state machine execution is waiting for Queue size to become 0, the queue size is consistent without any decrease.

![Screenshot 2022-09-21 at 6 08 50 PM](https://user-images.githubusercontent.com/89824590/191506072-bf530d4c-82a9-4713-b58b-a8a4b95d570e.png)
![Screenshot 2022-09-21 at 6 00 57 PM](https://user-images.githubusercontent.com/89824590/191506076-502f9fc6-0811-4e37-8da3-23fbaa131bcd.png)
![Screenshot 2022-09-21 at 6 00 06 PM](https://user-images.githubusercontent.com/89824590/191506090-0e3ff574-7019-4598-a2b7-776fd3fae20b.png)
![Screenshot 2022-09-21 at 10 12 45 AM](https://user-images.githubusercontent.com/89824590/191506196-bc3e7aca-bd4e-45d9-a1eb-561b3dfc87b9.png)

**Comment by matteofigus** [comment]
Thanks for the details. 
In general, you can use the waiters (currently at 3 seconds) to avoid reaching the 25K limit. By extending the time, you can allow less state transitions.

In any case, the problem here seems different, as when the Step Function checks the queue size, the ECS tasks should start and process the objects, but it doesn't seem to be happening here. A look into the Fargate logs in CloudWatch logs may give us some insights.
