### ISSUE TITLE
Security Vulnerabilities found in ECR repository

### ISSUE THREAD

**Issue by abhra-gupta-trakstar** [awslabs/amazon-s3-find-and-forget#361]
There are 4 Critical Vulnerabilities our Third Party Scanning Tool has exposed in the ECR Repository of the S3F2 Deletion Stack.
These seem to have been introduced by the base image (python:3.9.13)
**I am using S3F2 v:0.53**
Attached are the vulnerabilities which are classified as `Critical` by Snyk.
I have little to no idea where to start fixing the issue from. 
If you could point to a right direction in fixing these, that would be great!

[s3f2-delstack-109grp733tnhy-ecrrepository-asnjsln0ge7n_latest _ Snyk.pdf](https://github.com/awslabs/amazon-s3-find-and-forget/files/11331121/s3f2-delstack-109grp733tnhy-ecrrepository-asnjsln0ge7n_latest._.Snyk.pdf)

**Comment by ctd** [comment]
I believe this issue should be resolved by updating to v0.59 which was released today.

Please see the [updating instructions](https://github.com/awslabs/amazon-s3-find-and-forget/blob/master/docs/USER_GUIDE.md#updating-the-solution) for how to update your installation.

You can reopen this issue if you have any outstanding questions or concerns.
